config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User'
	belongs_to :quarter
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement
	belongs_to :user
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@quarters = Quarter.all
  	@clubs = Club.all
  	@events = Event.all
  	@recrutements = Recrutement.all
  	@requests = Request.all
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
        @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new 
    @user = current_user
        @quarters = Quarter.all
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @quarters = Quarter.all
  end

  # POST /clubs
  # POST /clubs.json
  def create
      @my_user = current_user.id
    @club = Club.create('name' => params[:name], 'category' => params[:category], quarter_id: params[:quarter_id])

  @club.admin_id =  @my_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to new_club_picture_path(@club.id), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])
    puts "*"*60
    puts params
    respond_to do |format|
      if @club.update(name: params['name'], category: params['category'])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(name: params['name'], category: params['category'])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@quarters = Quarter.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		puts "*"*60
		puts params
      if @user.update(first_name: params['first_name'] , last_name: params['last_name'], age: params['age'], description: params['description'], gender: params['gender'], pseudonym: params['pseudonym'], quarter: params['quarter'])
        
        puts "*"*60
		puts params
		flash[:success] = 'Votre profil a été mise à jour'
        redirect_to user_path
        
      else
      	flash[:success] = 'Il a eu une erreur dans votre action, veuillez réessayer'
        render '/users/:id/edit'
      end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<button><%= link_to 'Club', clubs_path %></button>

<button><%= link_to 'Event', events_path %></button>

<button><%= link_to 'Quarter', quarters_path %></button>

<button><%= link_to 'Recrutement', recrutements_path %></button>

<button><%= link_to 'Request', requests_path %></button>

app/views/layouts/_club.html.erb
 <% a = 0 %>
<% @clubs.each do |club| %>

  <% if club.admin.id == current_user.id %>
  <h1><%= link_to 'Mon club', club_path(club.id) %></h1>
    
  <% else %>
    <% a+= 1%>
  <% end %>
<% end %>
<%if a == @clubs.count %>
  <h1><%= link_to 'Créer un club', new_club_path %></h1>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>MALAGASPORT</title>
  <meta name="description" content="description here">
  <meta name="keywords" content="keywords,here">
  <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"> 
  <!--Replace with your tailwind.css once created-->
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application' %>
</head>

<body class="bg-gray-400 font-sans leading-normal tracking-normal">



  <nav class="flex items-center justify-between flex-wrap bg-white-800 p-6  w-full z-10 top-0 ">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a class="text-white no-underline hover:text-white hover:no-underline" href="#">
       <%= link_to root_path do %>
          <%= image_tag "logo.svg", :size => "180x110" %>
       <% end %>
      </a>
    </div>
    <div class="block lg:hidden">
      <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-white-600 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>

    </div>
    <div >

      <ul class="list-reset lg:flex justify-end flex-1 items-center">
<% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>

          <%= link_to "Profil", user_path(current_user.id), :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>

           <%= link_to "Liste des clubs", clubs_path , :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>

           <%= link_to "Liste des recrutements", recrutements_path , :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>
  <% else %>    
            <%= link_to "Se connecter", new_user_session_path,:class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>     
            <%= link_to "S'inscrire", new_user_registration_path, :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>   
      <% end %>
      </ul>
    </div>
  </nav>

  <!--Container-->
  <div class="container shadow-lg mx-auto bg-white mt-24 md:mt-18">

  </div>

  <script>
    //Javascript to toggle the menu
    document.getElementById('nav-toggle').onclick = function(){
      document.getElementById("nav-content").classList.toggle("hidden");
    }
  </script>

  <%= yield %>


<svg class="wave-top" viewBox="0 0 1439 147" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
   <g transform="translate(-1.000000, -14.000000)" fill-rule="nonzero">
     <g class="wave" fill="#f8fafc
">
       <path d="M1440,84 C1383.555,64.3 1342.555,51.3 1317,45 C1259.5,30.824 1206.707,25.526 1169,22 C1129.711,18.326 1044.426,18.475 980,22 C954.25,23.409 922.25,26.742 884,32 C845.122,37.787 818.455,42.121 804,45 C776.833,50.41 728.136,61.77 713,65 C660.023,76.309 621.544,87.729 584,94 C517.525,105.104 484.525,106.438 429,108 C379.49,106.484 342.823,104.484 319,102 C278.571,97.783 231.737,88.736 205,84 C154.629,75.076 86.296,57.743 0,32 L0,0 L1440,0 L1440,84 Z"></path>
     </g>
     <g transform="translate(1.000000, 15.000000)" fill="#FFFFFF
">
       <g transform="translate(719.500000, 68.500000) rotate(-180.000000) translate(-719.500000, -68.500000) ">
         <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
         <path d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z" opacity="0.100000001"></path>
         <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" opacity="0.200000003"></path>
       </g>
     </g>
   </g>
 </g>
</svg>
<!--Footer-->
<footer class="bg-gray">
  <div class="container mx-auto  px-8">

        <div class="w-full flex flex-col md:flex-row py-6">
        
      <div class="flex-1 mb-6">
      
       <%= link_to root_path do %>
          <%= image_tag "logo.svg", :size => "300x230" %>
       <% end %>
      </div>
    
    
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Links</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">FAQ</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Help</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Support</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Legal</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Terms</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Privacy</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Social</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Facebook</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Linkedin</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Twitter</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Company</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Official Blog</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">About Us</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
  

</footer>

  </body>
</html>